### ISSUE TITLE
problem1

### ISSUE THREAD

**Issue by willemNLP** [ArrowLuo/DOER#1]
你好，在运行的过程中出现了：tensorflow.python.framework.errors_impl.InvalidArgumentError: Can not squeeze dim[1], expected a dimension of 1, got 0 for 'cond/Squeeze' (op: 'Squeeze') with input shapes: [?,0,，] 这应该怎么解决呢

**Comment by ArrowLuo** [comment]
@willemNLP You should run `pip install requirements.txt` firstly. Because the TensorFlow version should be 1.2.0. Other versions may cause such issues.
