### ISSUE TITLE
Data format

### ISSUE THREAD

**Issue by yassmine-lam** [ArrowLuo/DOER#10]
Hi,

Thank u for sharing ur code with us.

I have a question about the data, how it is structred, are pos tags required for ur model?

given this example from ur data files:

cord NN NO B_AP NEUTRAL B_AP+NEUTRAL

why B_AP NEUTRAL is repeated twice??

Thank u

**Comment by ArrowLuo** [comment]
Hi @yassmine-lam, Sorry for the delayed reply. Maybe the same problem as #7. The `B_AP NEUTRAL B_AP+NEUTRAL` means three tags with two blank separators. `B_AP`, `NEUTRAL`, and `B_AP+NEUTRAL` denote aspect term, polarity, and collapsed label, respectively.

**Comment by ArrowLuo** [comment]
reopen if needed.
