### ISSUE TITLE
Cross domain evaluation

### ISSUE THREAD

**Issue by harshaljaiswal** [ArrowLuo/DOER#3]
Can we use the model trained on one domain for extraction of aspects from other domains

**Comment by ArrowLuo** [comment]
Hi @harshaljaiswal, I have never thought about this question, but it is interesting.
The answer is: yes, you can test the performance on cross-domain extraction. However, I deliberately think our model can not work well on this topic. The objective of the cross-domain is to transfer knowledge from a source domain to facilitate learning in a target domain, e.g., from restaurant to laptop. But, our cross-shared unit in our model is not designed to consider domain-shared information and domain-specific information.
