### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by LonieLee** [ArrowLuo/DOER#7]
1.请问laptop数据集中这五个标签的前两个代表什么NN NO B_AP POSITIVE B_AP+POSITIVE，后三个是不是表示是否是aspect,情感极性，以及联合标签
2.您的论文中提到emdedding部分采用的是DECNN的方法，但是DECNN中并没有对twitter数据集进行训练，twitter数据集的domain embedding是您自己训练的吗
3.方便提供一下twitter数据集和restaurant数据集吗

**Comment by ArrowLuo** [comment]
@LonieLee Sorry for the delayed reply.
1. NN means POS, NO/YES means whether this token is contained in the sentiment lexicon (Corresponding to the Section of Auxiliary Sentiment Lexicon Enhancement). The last three labels are what as you said.
2. We use embedding on twitter the same as the restaurant.
`We use Amazon embedding as the domain-specific word embeddings of $S_T$ as Amazon corpora is large and comprehensive although not in the same domain.`
3. We have updated the datasets. Check them in [data](https://github.com/ArrowLuo/DOER/tree/master/data) folder, please.

**Comment by LonieLee** [comment]
非常感谢您回答我，我还是不明白数据集中每个单词的第一个标签表示什么

**Comment by ArrowLuo** [comment]
@LonieLee 第一个标签是词性。
